CONFIG_NAME: '3stages'
DATASET_NAME: 'lsun-car'
DATA_DIR: '../data/LSUN_CAR'
SAVE_DIR: '../output/vis'
GPU_ID: '1'
WORKERS: 4

SUPER_CATEGORIES: 40
FINE_GRAINED_CATEGORIES: 500
TIED_CODES: True   # Do NOT change this to False during training.

TRAIN:
    # FLAG: True
    # NET_G: '../output/lsun-car_2020_09_24_06_13_24/Model/netG_600000_depth2.pth'  # Specify the generator path to resume training
    # NET_D: '../output/lsun-car_2020_09_24_06_13_24/Model/netD'  # Specify the discriminator path to resume training
    # NET_G: ''
    # NET_D: ''
    # MAX_EPOCH: 600
    # HARDNEG_MAX_ITER: 1500
    # SNAPSHOT_INTERVAL: 20000
    # SAVEMODEL_INTERVAL: 100000
    # SNAPSHOT_INTERVAL_HARDNEG: 1000
    # DISCRIMINATOR_LR: 0.0002
    # GENERATOR_LR: 0.0002
    BG_LOSS_WT_LCL: 0
    BG_LOSS_WT_GLB: 1
    BG_CLASSI_WT: 0
    DATASET_SIZE: 100000

    PRE_PAD: False
    RAND_PAD: True
    # PAD:     {4: 1, 8: 1, 16: 1, 32: 1, 64: 1, 128: 1, 256: 1}
    # PAD_ALT: {4: 1, 8: 1, 16: 1, 32: 1, 64: 1, 128: 1, 256: 1}
    # START_DEPTH: 2 # 32 has depth 0; should match loaded model depth
    # END_DEPTH: 3  # 512 has depth 3
    # BATCHSIZE_PER_DEPTH: [32, 16, 8, 3, 1]
    # BLEND_EPOCHS_PER_DEPTH: [0, 35, 0, 35, 35]
    # STABLE_EPOCHS_PER_DEPTH: [60, 60, 100, 60, 200]

GAN:
    DF_DIM: 64
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2
